[package]
name = "rust_inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
hamcrest2 = "0.3.0"
rstest = "0.24.0"
thiserror = "2.0.11"

[dev-dependencies]
stringreader = "0.1.1"
